# Generated by Django 2.0 on 2018-01-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productincart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзинах'},
        ),
    ]
