# Generated by Django 2.0 on 2018-01-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180124_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='session_key',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
