# Generated by Django 2.0 on 2018-01-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productincart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='session_key',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
