# Generated by Django 2.0 on 2018-01-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180125_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='size',
            field=models.IntegerField(default=30, verbose_name='Размер(см)'),
        ),
    ]
